name: "Sync docs with action.yml"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: npalm/action-docs-action@v1.1.0
      - uses: EndBug/add-and-commit@v8.0.2
        with:
          message: "Updating readme"
          add: README.md
